# Generated by Django 5.1.2 on 2024-10-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESOapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('FMS', 'Financial Management Services'), ('LS', 'Legal Services'), ('IRS', 'Investment-Readiness Services'), ('MC', 'Management Consulting'), ('ORS', 'Other Relevant Services')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
